PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS apps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  github_id INTEGER,
  github_owner TEXT,
  github_repo TEXT,
  github_full_name TEXT,
  github_url TEXT,
  source_url TEXT,
  download_url TEXT,
  website TEXT,
  website_url TEXT,
  docs_url TEXT,
  youtube_url TEXT,
  name TEXT,
  slug TEXT,
  category TEXT,
  logo TEXT,
  logo_url TEXT,
  logo_local_path TEXT,
  short_description TEXT,
  full_description TEXT,
  uses TEXT,
  alternative_of TEXT,
  maintainer_type TEXT,
  developer_name TEXT,
  developer_url TEXT,
  version TEXT,
  license TEXT,
  file_size INTEGER DEFAULT 0,
  tags TEXT,
  key_features TEXT,
  screenshots TEXT,
  comparison_table TEXT,
  supported_platforms TEXT,
  installation_methods TEXT,
  system_requirements TEXT,
  open_source_verified INTEGER DEFAULT 0,
  visibility TEXT DEFAULT 'private',
  added_by TEXT DEFAULT 'crawler',
  quality_score INTEGER DEFAULT 0,
  score INTEGER DEFAULT 0,
  status TEXT DEFAULT 'discovered',
  rejection_reason TEXT,
  duplicate_of_app_id INTEGER,
  duplicate_score INTEGER DEFAULT 0,
  stars INTEGER DEFAULT 0,
  forks INTEGER DEFAULT 0,
  watchers INTEGER DEFAULT 0,
  open_issues INTEGER DEFAULT 0,
  fork INTEGER DEFAULT 0,
  archived INTEGER DEFAULT 0,
  disabled INTEGER DEFAULT 0,
  language TEXT,
  topics TEXT,
  default_branch TEXT,
  package_names TEXT,
  has_releases INTEGER DEFAULT 0,
  latest_release_tag TEXT,
  latest_release_url TEXT,
  latest_release_at TEXT,
  last_commit_at TEXT,
  pushed_at TEXT,
  readme_markdown TEXT,
  readme_text TEXT,
  readme_quality_score INTEGER DEFAULT 0,
  docs_quality_score INTEGER DEFAULT 0,
  remote_openlib_id TEXT,
  dead_checked_at TEXT,
  dead_reason TEXT,
  last_crawled_at TEXT,
  last_ai_at TEXT,
  last_screenshot_at TEXT,
  last_synced_at TEXT,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS sync_queue (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  app_id INTEGER,
  action TEXT,
  payload TEXT,
  status TEXT DEFAULT 'pending',
  attempts INTEGER DEFAULT 0,
  last_error TEXT,
  next_attempt_at TEXT,
  openlib_response TEXT,
  synced INTEGER DEFAULT 0,
  created_at TEXT,
  updated_at TEXT,
  synced_at TEXT
);

CREATE TABLE IF NOT EXISTS screenshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  app_id INTEGER NOT NULL,
  source_url TEXT NOT NULL,
  local_path TEXT,
  webp_path TEXT,
  width INTEGER DEFAULT 0,
  height INTEGER DEFAULT 0,
  size_bytes INTEGER DEFAULT 0,
  content_hash TEXT,
  status TEXT DEFAULT 'pending',
  sort_order INTEGER DEFAULT 0,
  last_checked_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  UNIQUE(app_id, source_url)
);

CREATE TABLE IF NOT EXISTS crawl_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id TEXT,
  query TEXT,
  repo_full_name TEXT,
  github_id INTEGER,
  status TEXT,
  message TEXT,
  details TEXT,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS ai_jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  app_id INTEGER NOT NULL,
  task TEXT DEFAULT 'enrich',
  status TEXT DEFAULT 'pending',
  model TEXT,
  attempts INTEGER DEFAULT 0,
  input_hash TEXT,
  output TEXT,
  last_error TEXT,
  next_attempt_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  completed_at TEXT
);

CREATE TABLE IF NOT EXISTS update_jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  app_id INTEGER NOT NULL,
  job_type TEXT DEFAULT 'refresh',
  status TEXT DEFAULT 'pending',
  attempts INTEGER DEFAULT 0,
  last_error TEXT,
  next_attempt_at TEXT,
  created_at TEXT,
  updated_at TEXT,
  completed_at TEXT
);
